version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis/databases:/data
      - ./redis/config/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USERNAME}
  fullstack:
    image: fullstack:latest
    container_name: fullstack
    restart: always
    ports:
      - 3000:3000
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TTL=${REDIS_TTL}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - redis
      - mongo

  
networks:
  default:
    driver: bridge